### ISSUE TITLE
Some effects not work

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#13]
**Describe the bug**
When setting some effects, they do not work giving an error in the console.

Also, if I establish the poison effect, this does not cause an error in the console, but it is not being applied either.

**To Reproduce**
Set any of the effects (nausea, slowness, miningfatigue or poison)

**Expected behavior**
any effect should work without problem

**Screenshots**
![image](https://github.com/user-attachments/assets/b6470c91-173b-4b34-ac21-040bb2ab9dee)
![image](https://github.com/user-attachments/assets/17eea69c-d7e5-4384-ac60-238d0d0879f2)
![image](https://github.com/user-attachments/assets/746eecad-2a0f-4e05-87b4-161c11947318)

**Minecraft Version:**
- 1.20.4

**Server Version:**
 - Paper 1.20.4

**Plugin Version**
-  NoMoreCooked-0.0.9b-RELEASE

**Comment by The-Zandrax** [comment]
Hello !

I can see where the problem is due to changes between the latest versions and 1.20.4

I'll fix this today

**Comment by The-Zandrax** [comment]
Problem solved in **version 0.0.9c of NoMoreCooked** available on Spigot

Have a nice day!

**Comment by OODEK** [comment]
Thank you very much, I have sent a donation to your PayPal for the work.

Note: The poison effect still doesn't work, but it doesn't give an error on console either.
